name: Create Release PR

permissions:
  contents: write
  pull-requests: write
on:
  push:
    branches:
      - main

# Q: does this create the release and open a pull request or is the release only created after the PR is merged in??
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4