name: Release & Publish
# Note: Ideally the publish steps would be a separate workflow from the release-please action but we need the steps.release.outputs information

permissions:
  contents: write
  pull-requests: write
on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest
    # outputs:
    #   release-please: ${{ steps.release.outputs }}
    steps:
    - name: release please
      uses: google-github-actions/release-please-action@v4
      id: release
    # - name: send to output
    #   run: echo "release-please-output=${{}}" >> "$GITHUB_OUTPUT"
    
  publish:
    runs-on: ubuntu-latest
    needs: create-release
    strategy:
      matrix:
        path: ${{ needs.create-release.outputs.release.outputs.paths_released }}
    steps:
      - name: Echo github
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Echo needs
        env:
          NEEDS_CONTEXT: ${{ toJson(needs) }}
        run: echo "$NEEDS_CONTEXT"
      - name: Echo steps.release
        env:
          RELEASE_CONTEXT: ${{ toJson(steps.release) }}
        run: echo "$RELEASE_CONTEXT"
      # - name: Checkout Code
      #   uses: actions/checkout@v4
      #   # if: ${{ steps.release.outputs.releases_created }}
      # - name: Setup NodeJS
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '18.x'
      #     registry-url: 'https://registry.npmjs.org'
      #   # if: ${{ steps.release.outputs.releases_created }}
      # - name: NPM Install
      #   run: npm ci
      #   # if: ${{ steps.release.outputs.releases_created }}
      # - name: NPM Publish
      #   run: npm publish --access public
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      #   # if: ${{ steps.release.outputs.releases_created }}