name: Create Release PR
# Note: There's a small bug where this action will run when the PR of the release itself is merged. The Create Release step is run but doesn't do anything since only the changelog and package.json are updated there.

permissions:
  contents: write
  pull-requests: write
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - name: Echo
      #   env:
      #     GITHUB_CONTEXT: ${{ toJson(github) }}
      #   run: echo "$GITHUB_CONTEXT"
      - name: Create Release
        uses: google-github-actions/release-please-action@v4