name: Create Release

permissions:
  contents: write
  pull-requests: write
on:
  push:
    branches:
      - main

# env:
#   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: node
          path: web/packages/elements
          skip-github-release: true