name: Release & Publish
# Note: Ideally the publish steps would be a separate workflow from the release-please action but we need the steps.release.outputs information

permissions:
  contents: write
  pull-requests: write
on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      paths_released: ${{ steps.release-output.outputs.paths_released }}
      releases_created: ${{ steps.release-output.outputs.releases_created }}
    steps:
    - name: release please
      uses: google-github-actions/release-please-action@v4
      id: release
    - name: send to output
      id: release-output
      run: |
        echo "paths_released=${{steps.release.outputs.paths_released}}" >> $GITHUB_OUTPUT
        echo "releases_created=${{steps.release.outputs.releases_created}}" >> $GITHUB_OUTPUT
    
  publish:
    runs-on: ubuntu-latest
    needs: create-release
    if: ${{ needs.create-release.outputs.releases_created }}
    strategy:
      matrix:
        dir: ${{ fromJSON(needs.create-release.outputs.paths_released) }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - name: NPM Install
        working-directory: ${{ matrix.dir }}
        run: npm ci
      - name: NPM Publish
        working-directory: ${{ matrix.dir }}
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}