name: Create Release PR

permissions:
  contents: write
  pull-requests: write
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: node
          path: web/packages/elements
          include-component-in-tag: true
          # skip-github-release: true
          # skip-github-pull-request: true