name: Create Release PR

permissions:
  contents: write
  pull-requests: write
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
            
      - name: Create Release
        uses: google-github-actions/release-please-action@v4
        if: ${{ !contains(github.head_ref, 'release-please--branches--main--') }}
