name: Create Release PR

permissions:
  contents: write
  pull-requests: write
on:
  push:
    branches:
      - main
defaults:
  run:
    working-directory: web/packages/elements

# Q: does this create the release and open a pull request or is the release only created after the PR is merged in??
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
            
      - name: Create Release
        uses: google-github-actions/release-please-action@v4
        if: ${{ !startsWith(github.ref, 'release-please--branches--main--') }}
