name: Create Release PR
# Note: There's a small bug where this action will run when the PR of the release itself is merged. The Create Release step is run but doesn't do anything since only the changelog and package.json are updated there.

permissions:
  contents: write
  pull-requests: write
on:
  push:
    branches:
      - main

# defaults:
#   run:
#     working-directory: web/packages/elements
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo github
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Create Release
        uses: google-github-actions/release-please-action@v4
        id: release
      - name: Echo steps.release
        env:
          RELEASE_CONTEXT: ${{ toJson(steps.release) }}
        run: echo "$RELEASE_CONTEXT"
      - name: Checkout Code
        uses: actions/checkout@v4
        if: ${{ contains(github.head_ref, 'release-please--branches--main--') }}
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
        if: ${{ contains(github.head_ref, 'release-please--branches--main--') }}
      - name: NPM Install
        run: npm ci
        if: ${{ contains(github.head_ref, 'release-please--branches--main--') }}
      - name: NPM Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ contains(github.head_ref, 'release-please--branches--main--') }}