name: Create Release PR

permissions:
  contents: write
  pull-requests: write
on:
  push:
    branches:
      - main
defaults:
  run:
    working-directory: web/packages/elements

# Q: does this create the release and open a pull request or is the release only created after the PR is merged in??
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: google-github-actions/release-please-action@v4
        id: release
      - name: Checkout Code
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/checkout@v4
      - name: Setup NodeJS
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - name: NPM Install
        if: ${{ steps.release.outputs.releases_created }}
        run: npm ci
      - name: NPM Publish
        if: ${{ steps.release.outputs.releases_created }}
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
