name: Publish Package to NPM

permissions:
  actions: read
  contents: read
on:
  release:
    types: [ published ]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
defaults:
  run:
    working-directory: web/packages/elements
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

# bump the package version automatically using this command:
# npm version [patch | minor | major]