# name: Release

# on:
#   push:
#     branches:
#       - main

# permissions:
#   contents: write
#   pull-requests: write

# jobs:
#   release:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: google-github-actions/release-please-action@v4
#         id: release
#         with:
#           release-type: node
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: '18'

#       - name: Create Release
#         uses: google-github-actions/release-please-action@v4
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           release-type: node