name: Release & Publish
# Note: Ideally the publish steps would be a separate workflow from the release-please action but we need the steps.release.outputs information

permissions:
  contents: write
  pull-requests: write
on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      paths_released: ${{ steps.release.outputs.paths_released }}
      releases_created: ${{ steps.release.outputs.releases_created }}
    steps:
      - name: release please
        uses: google-github-actions/release-please-action@v4
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  publish:
    runs-on: ubuntu-latest
    needs: create-release
    defaults:
      run:
        working-directory: ${{ matrix.dir }}
    if: ${{ needs.create-release.outputs.releases_created == 'true' }}
    strategy:
      matrix:
        dir: ${{ fromJson(needs.create-release.outputs.paths_released) }}
    steps:
      - name: Echo need
        run: echo "$NEEDS_CONTEXT"
        env:
          NEEDS_CONTEXT: ${{ needs.create-release.outputs.paths_released }}
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org
      - name: NPM Install
        run: npm ci
      # - name: NPM Publish
      #   run: npm publish --access public
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
